
#weather_crud:
#  path: /weather
#  controller: App\Controller\WeatherCrudController:index

weather_in_city:
  path: /weather/{city}
  controller: App\Controller\WeatherController:cityAction
  requirements:
    city: \d+

weather_in_city_name:
  path: /weather/{country}/{cityName}
  controller: App\Controller\WeatherController:cityNameAction

weather_api_controller:
  path: /weather/api
  controller: App\Controller\WeatherApiController:getWeatherAction

app_logout:
  path: /logout
  methods: GET